{% set name = "bynder-sdk" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bynder-sdk-{{ version }}.tar.gz
  sha256: 9927cda0467ad4febfc84f284fc5b235107692bd5cfa2b0b0a934f0a33ab6908

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - requests >=2.20.0,<=3.0.0
    - requests-oauthlib >=1.1.0,<=2.0.0

test:
  imports:
    - bynder_sdk
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://bynder.com
  summary: Bynder SDK can be used to speed up the integration of Bynder in Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
